name: Deploy AutoML Platform

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-2
  CLUSTER_NAME: automl-eks-cluster
  TF_BUCKET: ${{ secrets.TF_BUCKET }}
  TF_KEY: terraform.tfstate
  ECR_API_REPO: ${{ secrets.ECR_API_REPO }}
  ECR_TRAINER_REPO: ${{ secrets.ECR_TRAINER_REPO }}

jobs:
  boostrap:
    name: Terraform boostrap
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    - name: Terraform Init (boostrap)
      run: |
        cd automl-platform/terraform/boostrap
        terraform init

    - name: Terraform Apply (boostrap)
      run: |
        cd automl-platform/terraform/boostrap
        terraform apply -auto-approve

  terraform:
    name: Terraform Main
    runs-on: ubuntu-latest
    needs: boostrap

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    - name: Terraform Init (Main)
      run: |
        cd automl-platform/terraform
        terraform init \
          -backend-config="bucket=${TF_BUCKET}" \
          -backend-config="key=${TF_KEY}" \
          -backend-config="region=${AWS_REGION}"

    - name: Terraform Apply (Main)
      run: |
        cd automl-platform/terraform
        terraform apply -auto-approve

  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push API Docker image
      run: |
        docker build -t automl-api ./automl-platform/api
        docker tag automl-api:latest $ECR_API_REPO:latest
        docker push $ECR_API_REPO:latest

    - name: Build and push Trainer Docker image
      run: |
        docker build -t automl-trainer ./automl-platform/trainer
        docker tag automl-trainer:latest $ECR_TRAINER_REPO:latest
        docker push $ECR_TRAINER_REPO:latest

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

    - name: Deploy to EKS
      run: |
        kubectl apply -f automl-platform/k8s/deployment.yaml
        kubectl apply -f automl-platform/k8s/service.yaml
